HTML_HELP_FILE:
  default: http://csdms.colorado.edu/wiki/Model_help:TopoFlow-Infiltration-Beven
  description: URL for HTML help file
  name: HTML help file
  type: String
I_gs_file:
  default: '[case_prefix]_2D-I.nc'
  description: filename for grid stack of I [m]
  name: Save I  grids file
  type: string
I_ts_file:
  default: '[case_prefix]_0D-I.txt'
  description: filename for time series of I [m]
  name: Save I  pixels file
  type: string
ModelAuthor:
  default: 'Scott D. Peckham '
  description: Name of the model author
  name: Author name
  type: String
ModelName:
  default: InfilBeven
  description: Name of the model
  name: Model name
  type: String
SAVE_I_GRIDS:
  default: 'No'
  description: option to save grids of cumul. infil. depth {Yes; No}
  name: Save I  grids toggle
  type: string
SAVE_I_PIXELS:
  default: 'No'
  description: option to save time series of cumul. infil. depth {Yes; No}
  name: Save I  pixels toggle
  type: string
SAVE_V0_GRIDS:
  default: 'No'
  description: option to save grids of infil. rate (at surf)  {Yes; No}
  name: Save v0 grids toggle
  type: string
SAVE_V0_PIXELS:
  default: 'No'
  description: option to save time series of infil. rate (at surf) {Yes; No}
  name: Save v0 pixels toggle
  type: string
case_prefix:
  default: Case5
  description: file prefix for the model scenario
  name: Case prefix
  type: string
comp_status:
  default: Enabled
  description: component status {Enabled; Disabled}
  name: Component status
  type: string
in_directory:
  default: /home/csdms/models/topoflow/3.1/share/data/treynor_iowa/
  description: input directory
  name: Input directory
  type: string
n_steps:
  default: '10'
  description: number of time steps
  name: Number of steps
  range:
    max: 1e7
    min: '1'
  type: long
out_directory:
  default: ~/CMT_Output/
  description: output directory
  name: Output directory
  type: string
pixel_file:
  default: '[case_prefix]_outlets.txt'
  description: filename for monitored pixel file
  name: Monitored pixel file
  type: string
save_grid_dt:
  default: '60.000'
  description: time interval between saved grids [sec]
  name: Save grid timestep
  range:
    max: 1e6
    min: '0.0'
  type: float
save_pixels_dt:
  default: '60.000'
  description: time interval between time series values [sec]
  name: Save pixels timestep
  range:
    max: 1e6
    min: '0.0'
  type: float
site_prefix:
  default: Treynor
  description: file prefix for the study site
  name: Site prefix
  type: string
v0_gs_file:
  default: '[case_prefix]_2D-v0.nc'
  description: filename for grid stack of v0 [m/s]
  name: Save v0 grids file
  type: string
v0_ts_file:
  default: '[case_prefix]_0D-v0.txt'
  description: filename for time series of v0 [m/s]
  name: Save v0 pixels file
  type: string
