- key: comp_status
  name: Component status
  description: component status {Enabled; Disabled}
  value:
    type: string
    default: Enabled
- key: in_directory
  name: Input directory
  description: input directory
  value:
    type: string
    default: /home/csdms/models/topoflow/3.1/share/data/treynor_iowa/
- key: out_directory
  name: Output directory
  description: output directory
  value:
    type: string
    default: ~/CMT_Output/
- key: site_prefix
  name: Site prefix
  description: file prefix for the study site
  value:
    type: string
    default: Treynor
- key: case_prefix
  name: Case prefix
  description: file prefix for the model scenario
  value:
    type: string
    default: Case5
- key: n_steps
  name: Number of steps
  description: number of time steps
  value:
    type: long
    default: '10'
    range:
      min: '1'
      max: 1e7
- key: save_grid_dt
  name: Save grid timestep
  description: time interval between saved grids [sec]
  value:
    type: float
    default: '60.000'
    range:
      min: '0.0'
      max: 1e6
- key: SAVE_V0_GRIDS
  name: Save v0 grids toggle
  description: option to save grids of infil. rate (at surf)  {Yes; No}
  value:
    type: string
    default: 'No'
- key: v0_gs_file
  name: Save v0 grids file
  description: filename for grid stack of v0 [m/s]
  value:
    type: string
    default: '[case_prefix]_2D-v0.nc'
- key: SAVE_I_GRIDS
  name: Save I  grids toggle
  description: option to save grids of cumul. infil. depth {Yes; No}
  value:
    type: string
    default: 'No'
- key: I_gs_file
  name: Save I  grids file
  description: filename for grid stack of I [m]
  value:
    type: string
    default: '[case_prefix]_2D-I.nc'
- key: save_pixels_dt
  name: Save pixels timestep
  description: time interval between time series values [sec]
  value:
    type: float
    default: '60.000'
    range:
      min: '0.0'
      max: 1e6
- key: pixel_file
  name: Monitored pixel file
  description: filename for monitored pixel file
  value:
    type: string
    default: '[case_prefix]_outlets.txt'
- key: SAVE_V0_PIXELS
  name: Save v0 pixels toggle
  description: option to save time series of infil. rate (at surf) {Yes; No}
  value:
    type: string
    default: 'No'
- key: v0_ts_file
  name: Save v0 pixels file
  description: filename for time series of v0 [m/s]
  value:
    type: string
    default: '[case_prefix]_0D-v0.txt'
- key: SAVE_I_PIXELS
  name: Save I  pixels toggle
  description: option to save time series of cumul. infil. depth {Yes; No}
  value:
    type: string
    default: 'No'
- key: I_ts_file
  name: Save I  pixels file
  description: filename for time series of I [m]
  value:
    type: string
    default: '[case_prefix]_0D-I.txt'
- key: ModelName
  name: Model name
  description: Name of the model
  value:
    type: String
    default: InfilBeven
- key: ModelAuthor
  name: Author name
  description: Name of the model author
  value:
    type: String
    default: 'Scott D. Peckham '
- key: HTML_HELP_FILE
  name: HTML help file
  description: URL for HTML help file
  value:
    type: String
    default: http://csdms.colorado.edu/wiki/Model_help:TopoFlow-Infiltration-Beven
