- key: comp_status
  name: Component status
  description: component status {Enabled; Disabled}
  value:
    type: string
    default: Enabled
- key: in_directory
  name: Input directory
  description: input directory
  value:
    type: string
    default: /home/csdms/models/topoflow/3.1/share/data/treynor_iowa/
- key: out_directory
  name: Output directory
  description: output directory
  value:
    type: string
    default: ~/CMT_Output/
- key: site_prefix
  name: Site prefix
  description: file prefix for the study site
  value:
    type: string
    default: Treynor
- key: case_prefix
  name: Case prefix
  description: file prefix for the model scenario
  value:
    type: string
    default: Case5
- key: n_steps
  name: Number of steps
  description: number of time steps
  value:
    type: long
    default: '10'
    range:
      min: '1'
      max: 1e7
- key: dt
  name: Time step
  description: timestep for snowmelt process [sec]
  value:
    type: float
    default: '3600.000'
    range:
      min: '0.0'
      max: 1e6
- key: Cp_snow_type
  name: Cp_snow type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: Cp_snow
  name: Cp_snow
  description: heat capacity of snow [J/kg/K]
  value:
    type: float
    default: '2090.000'
    range:
      min: '0.0'
      max: 3e3
- key: rho_snow_type
  name: rho_snow type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: rho_snow
  name: rho_snow
  description: density of snow [kg/m^3]
  value:
    type: float
    default: '300.000'
    range:
      min: '0.0'
      max: 1e3
- key: c0_type
  name: c0 type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: c0
  name: c0
  description: degree-day coefficient [mm/day/deg C]
  value:
    type: float
    default: '2.700'
    range:
      min: '0.0'
      max: 1e2
- key: T0_type
  name: T0 type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: T0
  name: T0
  description: reference temperature [deg C]
  value:
    type: float
    default: '-0.200'
    range:
      min: '-100'
      max: '100'
- key: h0_snow_type
  name: h0_snow type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: h0_snow
  name: h0_snow
  description: depth of snow [m]
  value:
    type: float
    default: '0.500'
    range:
      min: '0.0'
      max: '20.0'
- key: h0_swe_type
  name: h0_swe type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: h0_swe
  name: h0_swe
  description: depth of snow water equivalent (SWE) [m]
  value:
    type: float
    default: '0.150'
    range:
      min: '0.0'
      max: '20.0'
- key: save_grid_dt
  name: Save grid timestep
  description: time interval between saved grids [sec]
  value:
    type: float
    default: '60.000'
    range:
      min: '0'
      max: 1e6
- key: SAVE_MR_GRIDS
  name: Save mr grids toggle
  description: option to save grids of snow meltrate {Yes; No}
  value:
    type: string
    default: 'No'
- key: mr_gs_file
  name: Save mr grids file
  description: filename for grid stack of snow meltrate [m/s]
  value:
    type: string
    default: '[case_prefix]_2D-SMrate.nc'
- key: SAVE_HS_GRIDS
  name: Save hs grids toggle
  description: option to save grids of snow depth {Yes; No}
  value:
    type: string
    default: 'No'
- key: hs_gs_file
  name: Save hs grids file
  description: filename for grid stack of snow depth [m]
  value:
    type: string
    default: '[case_prefix]_2D-hsnow.nc'
- key: SAVE_SW_GRIDS
  name: Save sw grids toggle
  description: option to save grids of snow water equivalent {Yes; No}
  value:
    type: string
    default: 'No'
- key: sw_gs_file
  name: Save sw grids file
  description: filename for grid stack of snow water equivalent [m]
  value:
    type: string
    default: '[case_prefix]_2D-hswe.nc'
- key: SAVE_CC_GRIDS
  name: Save cc grids toggle
  description: option to save grids of cold content {Yes; No}
  value:
    type: string
    default: 'No'
- key: cc_gs_file
  name: Save cc grids file
  description: filename for grid stack of cold content [J/m^2]
  value:
    type: string
    default: '[case_prefix]_2D-Ecc.nc'
- key: save_pixels_dt
  name: Save pixels timestep
  description: time interval between time series values [sec]
  value:
    type: float
    default: '60.000'
    range:
      min: '0.0'
      max: 1e6
- key: pixel_file
  name: Monitored pixel file
  description: filename for monitored pixel file
  value:
    type: string
    default: '[case_prefix]_outlets.txt'
- key: SAVE_MR_PIXELS
  name: Save mr pixels toggle
  description: option to save time series of snow meltrate {Yes; No}
  value:
    type: string
    default: 'No'
- key: mr_ts_file
  name: Save mr pixels file
  description: filename for time series of  [m/s]
  value:
    type: string
    default: '[case_prefix]_0D-SMrate.txt'
- key: SAVE_HS_PIXELS
  name: Save hs pixels toggle
  description: option to save time series of snow depth {Yes; No}
  value:
    type: string
    default: 'No'
- key: hs_ts_file
  name: Save hs pixels file
  description: filename for time series of snow depth [m]
  value:
    type: string
    default: '[case_prefix]_0D-hsnow.txt'
- key: SAVE_SW_PIXELS
  name: Save sw pixels toggle
  description: option to save time series of snow water equivalent {Yes; No}
  value:
    type: string
    default: 'No'
- key: sw_ts_file
  name: Save sw pixels file
  description: filename for time series of snow water equivalent [m]
  value:
    type: string
    default: '[case_prefix]_0D-hswe.txt'
- key: SAVE_CC_PIXELS
  name: Save cc pixels toggle
  description: option to save time series of cold content {Yes; No}
  value:
    type: string
    default: 'No'
- key: cc_ts_file
  name: Save cc pixels file
  description: filename for time series of cold content [J/m^2]
  value:
    type: string
    default: '[case_prefix]_0D-Ecc.txt'
- key: ModelName
  name: Model name
  description: Name of the model
  value:
    type: String
    default: SnowDegreeDay
- key: ModelAuthor
  name: Author name
  description: Name of the model author
  value:
    type: String
    default: 'Scott D. Peckham '
- key: HTML_HELP_FILE
  name: HTML help file
  description: URL for HTML help file
  value:
    type: String
    default: http://csdms.colorado.edu/wiki/Model_help:TopoFlow-Snowmelt-Degree-Day
