- key: comp_status
  name: Component status
  description: component status {Enabled; Disabled}
  value:
    type: string
    default: Enabled
- key: in_directory
  name: Input directory
  description: input directory
  value:
    type: string
    default: /home/csdms/models/topoflow/3.1/share/data/treynor_iowa/
- key: out_directory
  name: Output directory
  description: output directory
  value:
    type: string
    default: ~/CMT_Output/
- key: site_prefix
  name: Site prefix
  description: file prefix for the study site
  value:
    type: string
    default: Treynor
- key: case_prefix
  name: Case prefix
  description: file prefix for the model scenario
  value:
    type: string
    default: Case5
- key: n_steps
  name: Number of steps
  description: number of time steps
  value:
    type: long
    default: '10'
    range:
      min: '1'
      max: 1e7
- key: dt
  name: Time step
  description: meteorology time step [sec]
  value:
    type: float
    default: '60.0'
    range:
      min: '0.0'
      max: 1e6
- key: rho_H2O_type
  name: rho_H2O type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: rho_H2O
  name: rho_H2O
  description: density of water [kg/m^3]
  value:
    type: float
    default: '1000.000'
    range:
      min: '0.0'
      max: '2000.0'
- key: Cp_air_type
  name: Cp_air type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: Cp_air
  name: Cp_air
  description: heat capacity of air [J/kg/K]
  value:
    type: float
    default: '1005.7000'
    range:
      min: '0.0'
      max: '2000.0'
- key: rho_air_type
  name: rho_air type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: rho_air
  name: rho_air
  description: density of air [kg/m^3]
  value:
    type: float
    default: '1.26139998'
    range:
      min: '0.0'
      max: '2.0'
- key: P_type
  name: precip. rates type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Time_Series
- key: P
  name: precip. rates
  description: precipitation rate [mm/hr]
  value:
    type: string
    default: '[case_prefix]_rain_rates.txt'
- key: PRECIP_ONLY
  name: PRECIP_ONLY toggle
  description: toggle to turn off all variable updates except precip. {Yes; No}
  value:
    type: string
    default: 'No'
- key: T_air_type
  name: T_air type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: T_air
  name: T_air
  description: temperature of air [deg C]
  value:
    type: float
    default: '20.000'
    range:
      min: '-100.0'
      max: '150.0'
- key: T_surf_type
  name: T_surf type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: T_surf
  name: T_surf
  description: temperature of surface [deg C]
  value:
    type: float
    default: '-5.000'
    range:
      min: '-100.0'
      max: '150.0'
- key: RH_type
  name: RH type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: RH
  name: RH
  description: relative humidity [none]
  value:
    type: float
    default: '0.500'
    range:
      min: '0.0'
      max: '1.0'
- key: p0_type
  name: p0 type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: p0
  name: p0
  description: atmospheric pressure [mbar]
  value:
    type: float
    default: '1000.000'
    range:
      min: '700.0'
      max: '1500.0'
- key: uz_type
  name: uz type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: uz
  name: uz
  description: wind velocity at height z [m/s]
  value:
    type: float
    default: '3.000'
    range:
      min: '0.0'
      max: '20.0'
- key: z_type
  name: z type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: z
  name: z
  description: wind reference height [m]
  value:
    type: float
    default: '10.000'
    range:
      min: '0.0'
      max: 1e3
- key: z0_air_type
  name: z0_air type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: z0_air
  name: z0_air
  description: surface roughness length scale for wind [m]
  value:
    type: float
    default: '0.0200'
    range:
      min: 1e-4
      max: 1e2
- key: albedo_type
  name: albedo type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: albedo
  name: albedo
  description: surface albedo in [0,1] [unitless]
  value:
    type: float
    default: '0.8'
    range:
      min: '0.0'
      max: '1.0'
- key: em_surf_type
  name: emissivity type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: em_surf
  name: emissivity
  description: surface emissivity in [0,1] [unitless]
  value:
    type: float
    default: '0.98'
    range:
      min: '0.0'
      max: '1.0'
- key: dust_atten_type
  name: dust atten. type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: dust_atten
  name: dust attenuation
  description: dust attenuation factor in [0,0.3], [unitless]
  value:
    type: float
    default: '0.08'
    range:
      min: '0.0'
      max: '0.3'
- key: cloud_factor_type
  name: cloud factor type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: cloud_factor
  name: cloud factor
  description: cloudiness factor, C,  in [0,1] (0 for no clouds)  [unitless]
  value:
    type: float
    default: '0.0'
    range:
      min: '0.0'
      max: '1.0'
- key: canopy_factor_type
  name: canopy factor type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: canopy_factor
  name: canopy factor
  description: canopy coverage factor, F, in [0,1],  [unitless]
  value:
    type: float
    default: '0.0'
    range:
      min: '0.0'
      max: '1.0'
- key: slope_grid_file
  name: slope grid file
  description: flat binary, row-major file with grid of 4-byte slopes
  value:
    type: string
    default: '[site_prefix]_slope.bin'
- key: aspect_grid_file
  name: aspect grid file
  description: flat binary, row-major file with grid of 4-byte aspects
  value:
    type: string
    default: '[site_prefix]_aspect.bin'
- key: GMT_offset
  name: time zone offset
  description: time zone offset from GMT {-12; -11; -10; -9; -8; -7; -6; -5; -4; -3;
    -2; -1; 0; 1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12}
  value:
    type: string
    default: '0'
- key: start_month
  name: start month
  description: start month {January; February; March; April; May; June; July; August;
    September; October; November; December}
  value:
    type: string
    default: January
- key: start_day
  name: start_day
  description: start day
  value:
    type: int
    default: '1'
    range:
      min: '0'
      max: '31'
- key: start_hour
  name: start_hour
  description: start hour
  value:
    type: float
    default: '0.0'
    range:
      min: '0.0'
      max: '23.99'
- key: save_grid_dt
  name: Save grid timestep
  description: time interval between saved grids [sec]
  value:
    type: float
    default: '60.000'
    range:
      min: '0.0'
      max: 1e6
- key: SAVE_EA_GRIDS
  name: Save e_air grids toggle
  description: option to save grids of vapor pressure (in air) {Yes; No}
  value:
    type: string
    default: 'No'
- key: ea_gs_file
  name: Save e_air grids toggle
  description: filename for grid stack of vapor pressure [mbar] (air)
  value:
    type: string
    default: '[case_prefix]_2D-eair.nc'
- key: SAVE_ES_GRIDS
  name: Save e_surf grids toggle
  description: option to save grids of vapor pressure (at surf) {Yes; No}
  value:
    type: string
    default: 'No'
- key: es_gs_file
  name: Save e_surf grids file
  description: filename for grid stack of vapor pressure [mbar] (surf)
  value:
    type: string
    default: '[case_prefix]_2D-esurf.nc'
- key: SAVE_QSW_GRIDS
  name: Save Qn_SW grids toggle
  description: option to save grids of net shortwave radiation {Yes; No}
  value:
    type: string
    default: 'No'
- key: Qsw_gs_file
  name: Save Qn_SW grids file
  description: filename for grid stack of net shortwave radiation [W/m^2]
  value:
    type: string
    default: '[case_prefix]_2D-QnSW.nc'
- key: SAVE_QLW_GRIDS
  name: Save Qn_LW grids toggle
  description: option to save grids of net longwave radiation {Yes; No}
  value:
    type: string
    default: 'No'
- key: Qlw_gs_file
  name: Save Qn_LW grids file
  description: filename for grid stack of net longwave radiation [W/m^2]
  value:
    type: string
    default: '[case_prefix]_2D-QnLW.nc'
- key: SAVE_EMA_GRIDS
  name: Save em_air grids toggle
  description: option to save grids of air emissivity {Yes; No}
  value:
    type: string
    default: 'No'
- key: ema_gs_file
  name: Save em_air grids file
  description: filename for grid stack of air emissivity in [0,1] [unitless]
  value:
    type: string
    default: '[case_prefix]_2D-emair.nc'
- key: save_pixels_dt
  name: Save pixels timestep
  description: time interval between time series values [sec]
  value:
    type: float
    default: '60.000'
    range:
      min: '0.0'
      max: 1e6
- key: pixel_file
  name: Monitored pixel file
  description: filename for monitored pixel file
  value:
    type: string
    default: '[case_prefix]_outlets.txt'
- key: SAVE_EA_PIXELS
  name: Save e_air pixels toggle
  description: option to save time series of sat. vapor press. (in air) {Yes; No}
  value:
    type: string
    default: 'No'
- key: ea_ts_file
  name: Save e_air pixels file
  description: filename for time series of sat. vapor press. [mbar] (in air)
  value:
    type: string
    default: '[case_prefix]_0D-eair.nc'
- key: SAVE_ES_PIXELS
  name: Save e_surf pixels toggle
  description: option to save time series of sat. vapor press. (at surf) {Yes; No}
  value:
    type: string
    default: 'No'
- key: es_ts_file
  name: Save e_surf pixels file
  description: filename for time series of sat. vapor press. [mbar] (at surf)
  value:
    type: string
    default: '[case_prefix]_0D-esurf.nc'
- key: SAVE_QSW_PIXELS
  name: Save Qn_SW pixels toggle
  description: option to save time series of net shortwave radiation {Yes; No}
  value:
    type: string
    default: 'No'
- key: Qsw_ts_file
  name: Save Qn_SW pixels file
  description: filename for time series of net shortwave radiation [W/m^2]
  value:
    type: string
    default: '[case_prefix]_0D-QnSW.nc'
- key: SAVE_QLW_PIXELS
  name: Save Qn_LW pixels toggle
  description: option to save time series of net longwave radiation {Yes; No}
  value:
    type: string
    default: 'No'
- key: Qlw_ts_file
  name: Save Qn_LW pixels file
  description: filename for time series of net longwave radiation [W/m^2]
  value:
    type: string
    default: '[case_prefix]_0D-QnLW.nc'
- key: SAVE_EMA_PIXELS
  name: Save em_air pixels toggle
  description: option to save time series of air emissivity {Yes; No}
  value:
    type: string
    default: 'No'
- key: ema_ts_file
  name: Save em_air pixels file
  description: filename for time series of air emissivity in [0,1] [unitless]
  value:
    type: string
    default: '[case_prefix]_0D-emair.nc'
- key: ModelName
  name: Model name
  description: Name of the model
  value:
    type: String
    default: Meteorology
- key: ModelAuthor
  name: Author name
  description: Name of the model author
  value:
    type: String
    default: 'Scott D. Peckham '
- key: HTML_HELP_FILE
  name: HTML help file
  description: URL for HTML help file
  value:
    type: String
    default: http://csdms.colorado.edu/wiki/Model_help:TopoFlow-Meteorology
