Cp_air:
  default: '1005.7000'
  description: heat capacity of air [J/kg/K]
  name: Cp_air
  range:
    max: '2000.0'
    min: '0.0'
  type: float
Cp_air_type:
  default: Scalar
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  name: Cp_air type
  type: string
GMT_offset:
  default: '0'
  description: time zone offset from GMT {-12; -11; -10; -9; -8; -7; -6; -5; -4; -3;
    -2; -1; 0; 1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12}
  name: time zone offset
  type: string
HTML_HELP_FILE:
  default: http://csdms.colorado.edu/wiki/Model_help:TopoFlow-Meteorology
  description: URL for HTML help file
  name: HTML help file
  type: String
ModelAuthor:
  default: 'Scott D. Peckham '
  description: Name of the model author
  name: Author name
  type: String
ModelName:
  default: Meteorology
  description: Name of the model
  name: Model name
  type: String
P:
  default: '[case_prefix]_rain_rates.txt'
  description: precipitation rate [mm/hr]
  name: precip. rates
  type: string
PRECIP_ONLY:
  default: 'No'
  description: toggle to turn off all variable updates except precip. {Yes; No}
  name: PRECIP_ONLY toggle
  type: string
P_type:
  default: Time_Series
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  name: precip. rates type
  type: string
Qlw_gs_file:
  default: '[case_prefix]_2D-QnLW.nc'
  description: filename for grid stack of net longwave radiation [W/m^2]
  name: Save Qn_LW grids file
  type: string
Qlw_ts_file:
  default: '[case_prefix]_0D-QnLW.nc'
  description: filename for time series of net longwave radiation [W/m^2]
  name: Save Qn_LW pixels file
  type: string
Qsw_gs_file:
  default: '[case_prefix]_2D-QnSW.nc'
  description: filename for grid stack of net shortwave radiation [W/m^2]
  name: Save Qn_SW grids file
  type: string
Qsw_ts_file:
  default: '[case_prefix]_0D-QnSW.nc'
  description: filename for time series of net shortwave radiation [W/m^2]
  name: Save Qn_SW pixels file
  type: string
RH:
  default: '0.500'
  description: relative humidity [none]
  name: RH
  range:
    max: '1.0'
    min: '0.0'
  type: float
RH_type:
  default: Scalar
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  name: RH type
  type: string
SAVE_EA_GRIDS:
  default: 'No'
  description: option to save grids of vapor pressure (in air) {Yes; No}
  name: Save e_air grids toggle
  type: string
SAVE_EA_PIXELS:
  default: 'No'
  description: option to save time series of sat. vapor press. (in air) {Yes; No}
  name: Save e_air pixels toggle
  type: string
SAVE_EMA_GRIDS:
  default: 'No'
  description: option to save grids of air emissivity {Yes; No}
  name: Save em_air grids toggle
  type: string
SAVE_EMA_PIXELS:
  default: 'No'
  description: option to save time series of air emissivity {Yes; No}
  name: Save em_air pixels toggle
  type: string
SAVE_ES_GRIDS:
  default: 'No'
  description: option to save grids of vapor pressure (at surf) {Yes; No}
  name: Save e_surf grids toggle
  type: string
SAVE_ES_PIXELS:
  default: 'No'
  description: option to save time series of sat. vapor press. (at surf) {Yes; No}
  name: Save e_surf pixels toggle
  type: string
SAVE_QLW_GRIDS:
  default: 'No'
  description: option to save grids of net longwave radiation {Yes; No}
  name: Save Qn_LW grids toggle
  type: string
SAVE_QLW_PIXELS:
  default: 'No'
  description: option to save time series of net longwave radiation {Yes; No}
  name: Save Qn_LW pixels toggle
  type: string
SAVE_QSW_GRIDS:
  default: 'No'
  description: option to save grids of net shortwave radiation {Yes; No}
  name: Save Qn_SW grids toggle
  type: string
SAVE_QSW_PIXELS:
  default: 'No'
  description: option to save time series of net shortwave radiation {Yes; No}
  name: Save Qn_SW pixels toggle
  type: string
T_air:
  default: '20.000'
  description: temperature of air [deg C]
  name: T_air
  range:
    max: '150.0'
    min: '-100.0'
  type: float
T_air_type:
  default: Scalar
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  name: T_air type
  type: string
T_surf:
  default: '-5.000'
  description: temperature of surface [deg C]
  name: T_surf
  range:
    max: '150.0'
    min: '-100.0'
  type: float
T_surf_type:
  default: Scalar
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  name: T_surf type
  type: string
albedo:
  default: '0.8'
  description: surface albedo in [0,1] [unitless]
  name: albedo
  range:
    max: '1.0'
    min: '0.0'
  type: float
albedo_type:
  default: Scalar
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  name: albedo type
  type: string
aspect_grid_file:
  default: '[site_prefix]_aspect.bin'
  description: flat binary, row-major file with grid of 4-byte aspects
  name: aspect grid file
  type: string
canopy_factor:
  default: '0.0'
  description: canopy coverage factor, F, in [0,1],  [unitless]
  name: canopy factor
  range:
    max: '1.0'
    min: '0.0'
  type: float
canopy_factor_type:
  default: Scalar
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  name: canopy factor type
  type: string
case_prefix:
  default: Case5
  description: file prefix for the model scenario
  name: Case prefix
  type: string
cloud_factor:
  default: '0.0'
  description: cloudiness factor, C,  in [0,1] (0 for no clouds)  [unitless]
  name: cloud factor
  range:
    max: '1.0'
    min: '0.0'
  type: float
cloud_factor_type:
  default: Scalar
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  name: cloud factor type
  type: string
comp_status:
  default: Enabled
  description: component status {Enabled; Disabled}
  name: Component status
  type: string
dt:
  default: '60.0'
  description: meteorology time step [sec]
  name: Time step
  range:
    max: 1e6
    min: '0.0'
  type: float
dust_atten:
  default: '0.08'
  description: dust attenuation factor in [0,0.3], [unitless]
  name: dust attenuation
  range:
    max: '0.3'
    min: '0.0'
  type: float
dust_atten_type:
  default: Scalar
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  name: dust atten. type
  type: string
ea_gs_file:
  default: '[case_prefix]_2D-eair.nc'
  description: filename for grid stack of vapor pressure [mbar] (air)
  name: Save e_air grids toggle
  type: string
ea_ts_file:
  default: '[case_prefix]_0D-eair.nc'
  description: filename for time series of sat. vapor press. [mbar] (in air)
  name: Save e_air pixels file
  type: string
em_surf:
  default: '0.98'
  description: surface emissivity in [0,1] [unitless]
  name: emissivity
  range:
    max: '1.0'
    min: '0.0'
  type: float
em_surf_type:
  default: Scalar
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  name: emissivity type
  type: string
ema_gs_file:
  default: '[case_prefix]_2D-emair.nc'
  description: filename for grid stack of air emissivity in [0,1] [unitless]
  name: Save em_air grids file
  type: string
ema_ts_file:
  default: '[case_prefix]_0D-emair.nc'
  description: filename for time series of air emissivity in [0,1] [unitless]
  name: Save em_air pixels file
  type: string
es_gs_file:
  default: '[case_prefix]_2D-esurf.nc'
  description: filename for grid stack of vapor pressure [mbar] (surf)
  name: Save e_surf grids file
  type: string
es_ts_file:
  default: '[case_prefix]_0D-esurf.nc'
  description: filename for time series of sat. vapor press. [mbar] (at surf)
  name: Save e_surf pixels file
  type: string
in_directory:
  default: /home/csdms/models/topoflow/3.1/share/data/treynor_iowa/
  description: input directory
  name: Input directory
  type: string
n_steps:
  default: '10'
  description: number of time steps
  name: Number of steps
  range:
    max: 1e7
    min: '1'
  type: long
out_directory:
  default: ~/CMT_Output/
  description: output directory
  name: Output directory
  type: string
p0:
  default: '1000.000'
  description: atmospheric pressure [mbar]
  name: p0
  range:
    max: '1500.0'
    min: '700.0'
  type: float
p0_type:
  default: Scalar
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  name: p0 type
  type: string
pixel_file:
  default: '[case_prefix]_outlets.txt'
  description: filename for monitored pixel file
  name: Monitored pixel file
  type: string
rho_H2O:
  default: '1000.000'
  description: density of water [kg/m^3]
  name: rho_H2O
  range:
    max: '2000.0'
    min: '0.0'
  type: float
rho_H2O_type:
  default: Scalar
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  name: rho_H2O type
  type: string
rho_air:
  default: '1.26139998'
  description: density of air [kg/m^3]
  name: rho_air
  range:
    max: '2.0'
    min: '0.0'
  type: float
rho_air_type:
  default: Scalar
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  name: rho_air type
  type: string
save_grid_dt:
  default: '60.000'
  description: time interval between saved grids [sec]
  name: Save grid timestep
  range:
    max: 1e6
    min: '0.0'
  type: float
save_pixels_dt:
  default: '60.000'
  description: time interval between time series values [sec]
  name: Save pixels timestep
  range:
    max: 1e6
    min: '0.0'
  type: float
site_prefix:
  default: Treynor
  description: file prefix for the study site
  name: Site prefix
  type: string
slope_grid_file:
  default: '[site_prefix]_slope.bin'
  description: flat binary, row-major file with grid of 4-byte slopes
  name: slope grid file
  type: string
start_day:
  default: '1'
  description: start day
  name: start_da
  range:
    max: '31'
    min: '0'
  type: int
start_hour:
  default: '0.0'
  description: start hour
  name: start_hou
  range:
    max: '23.99'
    min: '0.0'
  type: float
start_month:
  default: January
  description: start month {January; February; March; April; May; June; July; August;
    September; October; November; December}
  name: start mont
  type: string
uz:
  default: '3.000'
  description: wind velocity at height z [m/s]
  name: uz
  range:
    max: '20.0'
    min: '0.0'
  type: float
uz_type:
  default: Scalar
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  name: uz type
  type: string
z:
  default: '10.000'
  description: wind reference height [m]
  name: z
  range:
    max: 1e3
    min: '0.0'
  type: float
z0_air:
  default: '0.0200'
  description: surface roughness length scale for wind [m]
  name: z0_air
  range:
    max: 1e2
    min: 1e-4
  type: float
z0_air_type:
  default: Scalar
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  name: z0_air type
  type: string
z_type:
  default: Scalar
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  name: z type
  type: string
