- key: comp_status
  name: Component status
  description: component status {Enabled; Disabled}
  value:
    type: string
    default: Enabled
- key: in_directory
  name: Input directory
  description: input directory
  value:
    type: string
    default: /home/csdms/models/topoflow/3.1/share/data/treynor_iowa/
- key: out_directory
  name: Output directory
  description: output directory
  value:
    type: string
    default: ~/CMT_Output/
- key: site_prefix
  name: Site prefix
  description: file prefix for the study site
  value:
    type: string
    default: Treynor
- key: case_prefix
  name: Case prefix
  description: file prefix for the model scenario
  value:
    type: string
    default: Case5
- key: n_steps
  name: Number of steps
  description: number of time steps
  value:
    type: long
    default: '10'
    range:
      min: '1'
      max: 1e7
- key: n_layers
  name: Number of soil layers
  description: number of soil layers
  value:
    type: int
    default: '6'
    range:
      min: '1'
      max: '6'
- key: dt
  name: Time step
  description: timestep for subsurface flow [sec]
  value:
    type: float
    default: '3600.000'
    range:
      min: '0.0'
      max: 1e6
- key: elev_type
  name: DEM type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Grid
- key: elev
  name: DEM
  description: land surface elevation [m]
  value:
    type: string
    default: '[site_prefix]_DEM.rtg'
- key: h0_table_type
  name: h0_table type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: h0_table
  name: h0_table
  description: initial water table height [m]
  value:
    type: float
    default: '0.000'
    range:
      min: '0.0'
      max: 1e4
- key: d_freeze_type
  name: d_freeze type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: d_freeze
  name: d_freeze
  description: freeze depth below surface [m]
  value:
    type: float
    default: '0.000'
    range:
      min: '0.0'
      max: 1e4
- key: d_thaw_type
  name: d_thaw type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: d_thaw
  name: d_thaw
  description: thaw depth below surface [m]
  value:
    type: float
    default: '9999.000'
    range:
      min: '0.0'
      max: 1e4
- key: Ks_type_0
  name: K_sat type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: Ks_0
  name: K_sat
  description: sat. hydraulic conductivity [m/s]
  value:
    type: float
    default: '0.000050'
    range:
      min: '0.0'
      max: 1e-2
- key: qs_type_0
  name: theta_sat type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: qs_0
  name: theta_sat
  description: sat. soil water content [none]
  value:
    type: float
    default: '0.500'
    range:
      min: '0.0'
      max: '1.0'
- key: th_type_0
  name: thickness type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: th_0
  name: thickness
  description: soil layer thickness [m]
  value:
    type: float
    default: '0.100'
    range:
      min: '0.0'
      max: 1e3
- key: Ks_type_1
  name: K_sat type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: Ks_1
  name: K_sat
  description: sat. hydraulic conductivity [m/s]
  value:
    type: float
    default: '0.000050'
    range:
      min: '0.0'
      max: 1e-2
- key: qs_type_1
  name: theta_sat type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: qs_1
  name: theta_sat
  description: sat. soil water content [none]
  value:
    type: float
    default: '0.500'
    range:
      min: '0.0'
      max: '1.0'
- key: th_type_1
  name: thickness type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: th_1
  name: thickness
  description: soil layer thickness [m]
  value:
    type: float
    default: '0.100'
    range:
      min: '0.0'
      max: 1e3
- key: Ks_type_2
  name: K_sat type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: Ks_2
  name: K_sat
  description: sat. hydraulic conductivity [m/s]
  value:
    type: float
    default: '0.000050'
    range:
      min: '0.0'
      max: 1e-2
- key: qs_type_2
  name: theta_sat type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: qs_2
  name: theta_sat
  description: sat. soil water content [none]
  value:
    type: float
    default: '0.500'
    range:
      min: '0.0'
      max: '1.0'
- key: th_type_2
  name: thickness type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: th_2
  name: thickness
  description: soil layer thickness [m]
  value:
    type: float
    default: '0.100'
    range:
      min: '0.0'
      max: 1e3
- key: Ks_type_3
  name: K_sat type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: Ks_3
  name: K_sat
  description: sat. hydraulic conductivity [m/s]
  value:
    type: float
    default: '0.000050'
    range:
      min: '0.0'
      max: 1e-2
- key: qs_type_3
  name: theta_sat type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: qs_3
  name: theta_sat
  description: sat. soil water content [none]
  value:
    type: float
    default: '0.500'
    range:
      min: '0.0'
      max: '1.0'
- key: th_type_3
  name: thickness type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: th_3
  name: thickness
  description: soil layer thickness [m]
  value:
    type: float
    default: '0.100'
    range:
      min: '0.0'
      max: 1e3
- key: Ks_type_4
  name: K_sat type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: Ks_4
  name: K_sat
  description: sat. hydraulic conductivity [m/s]
  value:
    type: float
    default: '0.000050'
    range:
      min: '0.0'
      max: 1e-2
- key: qs_type_4
  name: theta_sat type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: qs_4
  name: theta_sat
  description: sat. soil water content [none]
  value:
    type: float
    default: '0.500'
    range:
      min: '0.0'
      max: '1.0'
- key: th_type_4
  name: thickness type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: th_4
  name: thickness
  description: soil layer thickness [m]
  value:
    type: float
    default: '0.100'
    range:
      min: '0.0'
      max: 1e3
- key: Ks_type_5
  name: K_sat type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: Ks_5
  name: K_sat
  description: sat. hydraulic conductivity [m/s]
  value:
    type: float
    default: '0.000050'
    range:
      min: '0.0'
      max: 1e-2
- key: qs_type_5
  name: theta_sat type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: qs_5
  name: theta_sat
  description: sat. soil water content [none]
  value:
    type: float
    default: '0.500'
    range:
      min: '0.0'
      max: '1.0'
- key: th_type_5
  name: thickness type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: th_5
  name: thickness
  description: soil layer thickness [m]
  value:
    type: float
    default: '0.100'
    range:
      min: '0.0'
      max: 1e3
- key: save_grid_dt
  name: Save grid timestep
  description: time interval between saved grids [sec]
  value:
    type: float
    default: '60.000'
    range:
      min: '0.0'
      max: 1e6
- key: SAVE_HT_GRIDS
  name: Save ht grids toggle
  description: option to save grids of water table height {Yes; No}
  value:
    type: string
    default: 'No'
- key: ht_gs_file
  name: Save ht grids file
  description: filename for grid stack of water table height [m]
  value:
    type: string
    default: '[case_prefix]_2D-htable.nc'
- key: SAVE_DF_GRIDS
  name: Save df grids toggle
  description: option to save grids of freeze depth {Yes; No}
  value:
    type: string
    default: 'No'
- key: df_gs_file
  name: Save df grids file
  description: filename for grid stack of freeze depth [m]
  value:
    type: string
    default: '[case_prefix]_2D-dfreeze.nc'
- key: SAVE_DT_GRIDS
  name: Save dt grids toggle
  description: option to save grids of thaw depth {Yes; No}
  value:
    type: string
    default: 'No'
- key: dt_gs_file
  name: Save dt grids file
  description: filename for grid stack of thaw depth [m]
  value:
    type: string
    default: '[case_prefix]_2D-dthaw.nc'
- key: save_pixels_dt
  name: Save pixels timestep
  description: time interval between time series values [sec]
  value:
    type: float
    default: '60.000'
    range:
      min: '0.0'
      max: 1e6
- key: pixel_file
  name: Monitored pixel file
  description: filename for monitored pixel file
  value:
    type: string
    default: '[case_prefix]_outlets.txt'
- key: SAVE_HT_PIXELS
  name: Save ht pixels toggle
  description: option to save time series of water table height {Yes; No}
  value:
    type: string
    default: 'No'
- key: ht_ts_file
  name: Save ht pixels file
  description: filename for time series of water table height [m]
  value:
    type: string
    default: '[case_prefix]_0D-htable.txt'
- key: SAVE_DF_PIXELS
  name: Save df pixels toggle
  description: option to save time series of freeze depth {Yes; No}
  value:
    type: string
    default: 'No'
- key: df_ts_file
  name: Save df pixels file
  description: filename for time series of freeze depth [m]
  value:
    type: string
    default: '[case_prefix]_0D-dfreeze.txt'
- key: SAVE_DT_PIXELS
  name: Save dt pixels toggle
  description: option to save time series of thaw depth {Yes; No}
  value:
    type: string
    default: 'No'
- key: dt_ts_file
  name: Save dt pixels file
  description: filename for time series of thaw depth [m]
  value:
    type: string
    default: '[case_prefix]_0D-dthaw.txt'
- key: ModelName
  name: Model name
  description: Name of the model
  value:
    type: String
    default: SatZoneDarcyLayers
- key: ModelAuthor
  name: Author name
  description: Name of the model author
  value:
    type: String
    default: 'Scott D. Peckham '
- key: HTML_HELP_FILE
  name: HTML help file
  description: URL for HTML help file
  value:
    type: String
    default: http://csdms.colorado.edu/wiki/Model_help:TopoFlow-Saturated_Zone-Darcy_Layers
