- key: comp_status
  name: Component status
  description: component status {Enabled; Disabled}
  value:
    type: string
    default: Enabled
- key: in_directory
  name: Input directory
  description: input directory
  value:
    type: string
    default: /home/csdms/models/topoflow/3.1/share/data/treynor_iowa/
- key: out_directory
  name: Output directory
  description: output directory
  value:
    type: string
    default: ~/CMT_Output/
- key: site_prefix
  name: Site prefix
  description: file prefix for the study site
  value:
    type: string
    default: Treynor
- key: case_prefix
  name: Case prefix
  description: file prefix for the model scenario
  value:
    type: string
    default: Case5
- key: n_steps
  name: Number of steps
  description: number of time steps
  value:
    type: long
    default: '10'
    range:
      min: '1'
      max: 1e7
- key: dt
  name: Time step
  description: channel process timestep [sec]
  value:
    type: float
    default: '6.00000000'
    range:
      min: '0'
      max: '100'
- key: code_file
  name: D8 flow code file
  description: grid of D8 flow codes in binary file [Jenson 84]
  value:
    type: string
    default: '[site_prefix]_flow.rtg'
- key: slope_file
  name: D8 slope file
  description: grid of D8 slopes in binary file [m/m]
  value:
    type: string
    default: '[site_prefix]_slope.rtg'
- key: MANNING
  name: Manning flag
  description: option to use Manning's n for roughness
  value:
    type: int
    default: '1'
    range:
      min: '0'
      max: '1'
- key: LAW_OF_WALL
  name: Law of Wall flag
  description: option to use Law of Wall for roughness
  value:
    type: int
    default: '0'
    range:
      min: '0'
      max: '1'
- key: nval_type
  name: Manning N type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Grid
- key: nval
  name: Manning N
  description: Manning's N values [s/m^(1/3)]
  value:
    type: string
    default: '[site_prefix]_chan-n.rtg'
- key: z0val_type
  name: Roughness z0 type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Grid
- key: z0val
  name: Roughness z0
  description: Law-of-wall roughness values [m]
  value:
    type: string
    default: '[site_prefix]_chan-z0.rtg'
- key: width_type
  name: Bed width type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Grid
- key: width
  name: Bed width
  description: bottom width of trapezoid cross-section [m]
  value:
    type: string
    default: '[site_prefix]_chan-w.rtg'
- key: angle_type
  name: Bank angle type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Grid
- key: angle
  name: Bank angle
  description: bank angle of trapezoid cross-section [deg]
  value:
    type: string
    default: '[site_prefix]_chan-a.rtg'
- key: d0_type
  name: Init. depth type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: d0
  name: Init. depth
  description: initial flow depth [m]  (if Scalar, use 0.0!)
  value:
    type: float
    default: '0.00000000'
    range:
      min: '0.0'
      max: '0.1'
- key: sinu_type
  name: Sinuosity type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: sinu
  name: Sinuosity
  description: absolute channel sinuosity [m/m]
  value:
    type: float
    default: '1.00000000'
    range:
      min: '0.0'
      max: '3.0'
- key: save_grid_dt
  name: Save grid timestep
  description: time interval between saved grids [sec]
  value:
    type: float
    default: '60.00000000'
    range:
      min: '0.0'
      max: 1e6
- key: SAVE_Q_GRIDS
  name: Save Q grids toggle
  description: option to save computed Q grids {Yes; No}
  value:
    type: string
    default: 'Yes'
- key: Q_gs_file
  name: Save Q grids file
  description: filename for Q grid stack [m^3/s]
  value:
    type: string
    default: '[case_prefix]_2D-Q.nc'
- key: SAVE_U_GRIDS
  name: Save u grids toggle
  description: option to save computed u grids {Yes; No}
  value:
    type: string
    default: 'No'
- key: u_gs_file
  name: Save u grids file
  description: filename for u grid stack [m/s]
  value:
    type: string
    default: '[case_prefix]_2D-u.nc'
- key: SAVE_D_GRIDS
  name: Save d grids toggle
  description: option to save computed d grids {Yes; No}
  value:
    type: string
    default: 'No'
- key: d_gs_file
  name: Save d grids file
  description: filename for d grid stack [m]
  value:
    type: string
    default: '[case_prefix]_2D-d.nc'
- key: SAVE_F_GRIDS
  name: Save f grids toggle
  description: option to save computed f grids {Yes; No}
  value:
    type: string
    default: 'No'
- key: f_gs_file
  name: Save f grids file
  description: filename for f grid stack [none]
  value:
    type: string
    default: '[case_prefix]_2D-f.nc'
- key: save_pixels_dt
  name: Save pixels timestep
  description: time interval between time series values [sec]
  value:
    type: float
    default: '60.00000000'
    range:
      min: '0.0'
      max: 1e6
- key: pixel_file
  name: Monitored pixel file
  description: filename for monitored pixel file
  value:
    type: string
    default: '[case_prefix]_outlets.txt'
- key: SAVE_Q_PIXELS
  name: Save Q pixels toggle
  description: option to save computed Q time series {Yes; No}
  value:
    type: string
    default: 'Yes'
- key: Q_ts_file
  name: Save Q pixels file
  description: filename for computed Q time series [m^3/s]
  value:
    type: string
    default: '[case_prefix]_0D-Q.txt'
- key: SAVE_U_PIXELS
  name: Save u pixels toggle
  description: option to save computed u time series {Yes; No}
  value:
    type: string
    default: 'No'
- key: u_ts_file
  name: Save u pixels file
  description: filename for computed u time series [m/s]
  value:
    type: string
    default: '[case_prefix]_0D-u.txt'
- key: SAVE_D_PIXELS
  name: Save d pixels toggle
  description: option to save computed d time series {Yes; No}
  value:
    type: string
    default: 'No'
- key: d_ts_file
  name: Save d pixels file
  description: filename for computed d time series [m]
  value:
    type: string
    default: '[case_prefix]_0D-d.txt'
- key: SAVE_F_PIXELS
  name: Save f pixels toggle
  description: option to save computed f time series {Yes; No}
  value:
    type: string
    default: 'No'
- key: f_ts_file
  name: Save f pixels file
  description: filename for computed f time series [none]
  value:
    type: string
    default: '[case_prefix]_0D-f.txt'
- key: ModelName
  name: Model name
  description: Name of the model
  value:
    type: String
    default: ChannelsKinWave
- key: ModelAuthor
  name: Author name
  description: Name of the model author
  value:
    type: String
    default: 'Scott D. Peckham '
- key: HTML_HELP_FILE
  name: HTML help file
  description: URL for HTML help file
  value:
    type: String
    default: http://csdms.colorado.edu/wiki/Model_help:TopoFlow-Channels-Kinematic_Wave
