HTML_HELP_FILE:
  default: http://csdms.colorado.edu/help/models/topoflow/TF_tutorial.htm
  description: URL for HTML help file
  name: HTML help file
  type: String
ModelAuthor:
  default: 'Scott D. Peckham '
  description: Name of the model author
  name: Author name
  type: String
ModelName:
  default: TestService
  description: Name of the model
  name: Model name
  type: String
case_prefix:
  default: Case5
  description: file prefix for the model scenario
  name: Case prefix
  type: String
comp_status:
  default: Enabled
  description: component status {Enabled; Disabled}
  name: Component status
  type: String
in_directory:
  default: /home/csdms/models/topoflow/3.1/share/data/treynor_iowa/
  description: input directory
  name: Input directory
  type: String
out_directory:
  default: ~/CMT_Output/
  description: output directory
  name: Output directory
  type: String
site_prefix:
  default: Treynor
  description: file prefix for the study site
  name: Site prefix
  type: String
