- key: comp_status
  name: Component status
  description: component status
  value:
    type: choice
    default: Enabled
    choices:
    - Enabled
    - Disabled
  units: None
- key: in_directory
  name: Input directory
  description: input directory
  value:
    type: String
    default: /home/csdms/models/topoflow/3.1/share/data/treynor_iowa/
  units: None
- key: out_directory
  name: Output directory
  description: output directory
  value:
    type: String
    default: ~/CMT_Output/
  units: None
- key: site_prefix
  name: Site prefix
  description: file prefix for the study site
  value:
    type: String
    default: Treynor
  units: None
- key: case_prefix
  name: Case prefix
  description: file prefix for the model scenario
  value:
    type: String
    default: Case5
  units: None
- key: ModelName
  name: Model name
  description: Name of the model
  value:
    type: String
    default: TestService
  units: None
- key: ModelAuthor
  name: Author name
  description: Name of the model author
  value:
    type: String
    default: 'Scott D. Peckham '
  units: None
- key: HTML_HELP_FILE
  name: HTML help file
  description: URL for HTML help file
  value:
    type: String
    default: http://csdms.colorado.edu/help/models/topoflow/TF_tutorial.htm
  units: None
