- key: comp_status
  name: Component status
  description: component status {Enabled; Disabled}
  value:
    type: string
    default: Enabled
- key: in_directory
  name: Input directory
  description: input directory
  value:
    type: string
    default: /home/csdms/models/topoflow/3.1/share/data/treynor_iowa/
- key: out_directory
  name: Output directory
  description: output directory
  value:
    type: string
    default: ~/CMT_Output/
- key: site_prefix
  name: Site prefix
  description: file prefix for the study site
  value:
    type: string
    default: Treynor
- key: case_prefix
  name: Case prefix
  description: file prefix for the model scenario
  value:
    type: string
    default: Case5
- key: n_steps
  name: Number of steps
  description: number of time steps
  value:
    type: long
    default: '10'
    range:
      min: '1'
      max: 1e7
- key: dt
  name: Time step
  description: timestep for evaporation rate [sec]
  value:
    type: float
    default: '10800.000'
    range:
      min: '0.0'
      max: 1e4
- key: ET_rate
  name: ET rate
  description: Grid Sequence [mm/hr]
  value:
    type: string
    default: '[case_prefix]_2D-ETrate-in.nc'
- key: save_grid_dt
  name: Save grid timestep
  description: time interval between saved grids [sec]
  value:
    type: float
    default: '60.000'
    range:
      min: '0.0'
      max: 1e6
- key: SAVE_ER_GRIDS
  name: Save er grids toggle
  description: option to save grids of evap. rate [mm/hr] {Yes; No}
  value:
    type: string
    default: 'No'
- key: er_gs_file
  name: Save er grids file
  description: filename for grid stack of evap. rate [mm/hr]
  value:
    type: string
    default: '[case_prefix]_2D-ETrate.nc'
- key: save_pixels_dt
  name: Save pixels timestep
  description: time interval between time series values [sec]
  value:
    type: float
    default: '60.000'
    range:
      min: '0.0'
      max: 1e6
- key: pixel_file
  name: Monitored pixel file
  description: filename for monitored pixel file
  value:
    type: string
    default: '[case_prefix]_outlets.txt'
- key: SAVE_ER_PIXELS
  name: Save er pixels toggle
  description: option to save time series of evap. rate {Yes; No}
  value:
    type: string
    default: 'No'
- key: er_ts_file
  name: Save er pixels file
  description: filename for time series of evap. rate [mm/hr]
  value:
    type: string
    default: '[case_prefix]_0D-ETrate.txt'
- key: ModelName
  name: Model name
  description: Name of the model
  value:
    type: String
    default: EvapReadFile
- key: ModelAuthor
  name: Author name
  description: Name of the model author
  value:
    type: String
    default: 'Scott D. Peckham '
- key: HTML_HELP_FILE
  name: HTML help file
  description: URL for HTML help file
  value:
    type: String
    default: http://csdms.colorado.edu/wiki/Model_help:TopoFlow-Evaporation-Read_File
