- key: comp_status
  name: Component status
  description: component status {Enabled; Disabled}
  value:
    type: string
    default: Enabled
- key: in_directory
  name: Input directory
  description: input directory
  value:
    type: string
    default: /home/csdms/models/topoflow/3.1/share/data/treynor_iowa/
- key: out_directory
  name: Output directory
  description: output directory
  value:
    type: string
    default: ~/CMT_Output/
- key: site_prefix
  name: Site prefix
  description: file prefix for the study site
  value:
    type: string
    default: Treynor
- key: case_prefix
  name: Case prefix
  description: file prefix for the model scenario
  value:
    type: string
    default: Case5
- key: n_steps
  name: Number of steps
  description: number of time steps
  value:
    type: long
    default: '10'
    range:
      min: '1'
      max: 1e7
- key: n_layers
  name: Number of soil layers
  description: number of soil layers
  value:
    type: int
    default: '1'
    range:
      min: '1'
      max: '3'
- key: dt
  name: Time step
  description: timestep for infiltration process [sec]
  value:
    type: float
    default: '60.000'
    range:
      min: '0'
      max: 1e3
- key: Ks_type_0
  name: K_sat type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: Ks_0
  name: K_sat
  description: sat. hydraulic conductivity [m/s]
  value:
    type: float
    default: '0.00000720'
    range:
      min: '0.0'
      max: 1e-2
- key: Ki_type_0
  name: K_init type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: Ki_0
  name: K_init
  description: init. hydraulic conductivity [m/s] (< K_sat)
  value:
    type: float
    default: '0.00000010'
    range:
      min: '0.0'
      max: 1e-2
- key: qs_type_0
  name: theta_sat type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: qs_0
  name: theta_sat
  description: sat. soil water content [none]
  value:
    type: float
    default: '0.48500000'
    range:
      min: '0.0'
      max: '1.0'
- key: qi_type_0
  name: theta_init type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: qi_0
  name: theta_init
  description: init. soil water content [none] (< theta_sat)
  value:
    type: float
    default: '0.37580763'
    range:
      min: '0.0'
      max: '1.0'
- key: G_type_0
  name: G type
  description: allowed input types {Scalar; Grid; Time_Series; Grid_Sequence}
  value:
    type: string
    default: Scalar
- key: G_0
  name: G
  description: capillary length scale [m]
  value:
    type: float
    default: '0.72400000'
    range:
      min: '0.0'
      max: 1e2
- key: soil_type_0
  name: Closest soil_type
  description: closest standard soil type {sand; loamy_sand; sandy_loam; silty_loam;
    loam; sandy_clay_loam; silty_clay_loam; clay_loam; sandy_clay; silty_clay; clay}
  value:
    type: string
    default: silty_loam
- key: save_grid_dt
  name: Save grid timestep
  description: time interval between saved grids [sec]
  value:
    type: float
    default: '60.000'
    range:
      min: '0.0'
      max: 1e6
- key: SAVE_V0_GRIDS
  name: Save v0 grids toggle
  description: option to save grids of infil. rate (at surf)  {Yes; No}
  value:
    type: string
    default: 'No'
- key: v0_gs_file
  name: Save v0 grids file
  description: filename for grid stack of v0 [m/s]
  value:
    type: string
    default: '[case_prefix]_2D-v0.nc'
- key: SAVE_I_GRIDS
  name: Save I  grids toggle
  description: option to save grids of cumul. infil. depth {Yes; No}
  value:
    type: string
    default: 'No'
- key: I_gs_file
  name: Save I  grids file
  description: filename for grid stack of I [m]
  value:
    type: string
    default: '[case_prefix]_2D-I.nc'
- key: save_pixels_dt
  name: Save pixels timestep
  description: time interval between time series values [sec]
  value:
    type: float
    default: '60.000'
    range:
      min: '0.0'
      max: 1e6
- key: pixel_file
  name: Monitored pixel file
  description: filename for monitored pixel file
  value:
    type: string
    default: '[case_prefix]_outlets.txt'
- key: SAVE_V0_PIXELS
  name: Save v0 pixels toggle
  description: option to save time series of infil. rate (at surf) {Yes; No}
  value:
    type: string
    default: 'No'
- key: v0_ts_file
  name: Save v0 pixels file
  description: filename for time series of v0 [m/s]
  value:
    type: string
    default: '[case_prefix]_0D-v0.txt'
- key: SAVE_I_PIXELS
  name: Save I  pixels toggle
  description: option to save time series of cumul. infil. depth {Yes; No}
  value:
    type: string
    default: 'No'
- key: I_ts_file
  name: Save I  pixels file
  description: filename for time series of I [m]
  value:
    type: string
    default: '[case_prefix]_0D-I.txt'
- key: ModelName
  name: Model name
  description: Name of the model
  value:
    type: String
    default: InfilGreenAmpt
- key: ModelAuthor
  name: Author name
  description: Name of the model author
  value:
    type: String
    default: 'Scott D. Peckham '
- key: HTML_HELP_FILE
  name: HTML help file
  description: URL for HTML help file
  value:
    type: String
    default: http://csdms.colorado.edu/wiki/Model_help:TopoFlow-Infiltration-Green-Ampt
