- key: comp_status
  name: Component status
  description: component status {Enabled; Disabled}
  value:
    type: string
    default: Enabled
- key: in_directory
  name: Input directory
  description: input directory
  value:
    type: string
    default: /home/csdms/models/topoflow/3.1/share/data/treynor_iowa/
- key: out_directory
  name: Output directory
  description: output directory
  value:
    type: string
    default: ~/CMT_Output/
- key: site_prefix
  name: Site prefix
  description: file prefix for the study site
  value:
    type: string
    default: Treynor
- key: case_prefix
  name: Case prefix
  description: file prefix for the model scenario
  value:
    type: string
    default: Case5
- key: use_sources
  name: Use sources toggle
  description: option to use sources {Yes; No}
  value:
    type: string
    default: 'No'
- key: source_file
  name: Sources file
  description: source information file
  value:
    type: string
    default: '[site_prefix]_sources.txt'
- key: use_sinks
  name: Use sinks toggle
  description: option to use sinks {Yes; No}
  value:
    type: string
    default: 'No'
- key: sink_file
  name: Sinks file
  description: sink information file
  value:
    type: string
    default: '[site_prefix]_sinks.txt'
- key: use_canals
  name: Use canals toggle
  description: option to use canals {Yes; No}
  value:
    type: string
    default: 'No'
- key: canal_file
  name: Canal file
  description: canal information file
  value:
    type: string
    default: '[site_prefix]_canals.txt'
- key: ModelName
  name: Model name
  description: Name of the model
  value:
    type: String
    default: DiversionsFraction
- key: ModelAuthor
  name: Author name
  description: Name of the model author
  value:
    type: String
    default: 'Scott D. Peckham '
- key: HTML_HELP_FILE
  name: HTML help file
  description: URL for HTML help file
  value:
    type: String
    default: http://csdms.colorado.edu/wiki/Model_help:TopoFlow-Diversions
