- key: comp_status
  name: Component status
  description: component status
  value:
    type: choice
    default: Enabled
    choices:
    - Enabled
    - Disabled
  units: None
- key: in_directory
  name: Input directory
  description: input directory
  value:
    type: string
    default: /home/csdms/models/topoflow/3.1/share/data/treynor_iowa/
  units: None
- key: out_directory
  name: Output directory
  description: output directory
  value:
    type: string
    default: ~/CMT_Output/
  units: None
- key: site_prefix
  name: Site prefix
  description: file prefix for the study site
  value:
    type: string
    default: Treynor
  units: None
- key: case_prefix
  name: Case prefix
  description: file prefix for the model scenario
  value:
    type: string
    default: Case5
  units: None
- key: n_steps
  name: Number of steps
  description: number of time steps
  value:
    type: long
    default: '10'
    range:
      min: '1'
      max: 1e7
  units: None
- key: dt
  name: Time step
  description: channel process timestep
  value:
    type: float
    default: '6.00000000'
    range:
      min: '0'
      max: '100'
  units: sec
- key: code_file
  name: D8 flow code file
  description: grid of D8 flow codes in binary file (Jenson 84)
  value:
    type: string
    default: '[site_prefix]_flow.rtg'
  units: None
- key: slope_file
  name: D8 slope file
  description: grid of D8 slopes in binary file
  value:
    type: string
    default: '[site_prefix]_slope.rtg'
  units: m/m
- key: MANNING
  name: Manning flag
  description: option to use Manning's n for roughness
  value:
    type: int
    default: '1'
    range:
      min: '0'
      max: '1'
  units: None
- key: LAW_OF_WALL
  name: Law of Wall flag
  description: option to use Law of Wall for roughness
  value:
    type: int
    default: '0'
    range:
      min: '0'
      max: '1'
  units: None
- key: nval_type
  name: Manning N type
  description: allowed input types
  value:
    type: choice
    default: Grid
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
  units: None
- key: nval
  name: Manning N
  description: Manning's N values
  value:
    type: string
    default: '[site_prefix]_chan-n.rtg'
  units: s/m^(1/3)
- key: z0val_type
  name: Roughness z0 type
  description: allowed input types
  value:
    type: choice
    default: Grid
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
  units: None
- key: z0val
  name: Roughness z0
  description: Law-of-wall roughness values
  value:
    type: string
    default: '[site_prefix]_chan-z0.rtg'
  units: m
- key: width_type
  name: Bed width type
  description: allowed input types
  value:
    type: choice
    default: Grid
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
  units: None
- key: width
  name: Bed width
  description: bottom width of trapezoid cross-section
  value:
    type: string
    default: '[site_prefix]_chan-w.rtg'
  units: m
- key: angle_type
  name: Bank angle type
  description: allowed input types
  value:
    type: choice
    default: Grid
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
  units: None
- key: angle
  name: Bank angle
  description: bank angle of trapezoid cross-section
  value:
    type: string
    default: '[site_prefix]_chan-a.rtg'
  units: deg
- key: d0_type
  name: Init. depth type
  description: allowed input types
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
  units: None
- key: d0
  name: Init. depth
  description: initial flow depth (if Scalar, use 0.0!)
  value:
    type: float
    default: '0.00000000'
    range:
      min: '0.0'
      max: '0.1'
  units: m
- key: sinu_type
  name: Sinuosity type
  description: allowed input types
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
  units: None
- key: sinu
  name: Sinuosity
  description: absolute channel sinuosity
  value:
    type: float
    default: '1.00000000'
    range:
      min: '0.0'
      max: '3.0'
  units: m/m
- key: save_grid_dt
  name: Save grid timestep
  description: time interval between saved grids
  value:
    type: float
    default: '60.00000000'
    range:
      min: '0.0'
      max: 1e6
  units: sec
- key: SAVE_Q_GRIDS
  name: Save Q grids toggle
  description: option to save computed Q grids
  value:
    type: choice
    default: 'Yes'
    choices:
    - 'Yes'
    - 'No'
  units: None
- key: Q_gs_file
  name: Save Q grids file
  description: filename for Q grid stack
  value:
    type: string
    default: '[case_prefix]_2D-Q.nc'
  units: m^3/s
- key: SAVE_U_GRIDS
  name: Save u grids toggle
  description: option to save computed u grids
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
  units: None
- key: u_gs_file
  name: Save u grids file
  description: filename for u grid stack
  value:
    type: string
    default: '[case_prefix]_2D-u.nc'
  units: m/s
- key: SAVE_D_GRIDS
  name: Save d grids toggle
  description: option to save computed d grids
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
  units: None
- key: d_gs_file
  name: Save d grids file
  description: filename for d grid stack
  value:
    type: string
    default: '[case_prefix]_2D-d.nc'
  units: m
- key: SAVE_F_GRIDS
  name: Save f grids toggle
  description: option to save computed f grids
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
  units: None
- key: f_gs_file
  name: Save f grids file
  description: filename for f grid stack
  value:
    type: string
    default: '[case_prefix]_2D-f.nc'
  units: None
- key: save_pixels_dt
  name: Save pixels timestep
  description: time interval between time series values
  value:
    type: float
    default: '60.00000000'
    range:
      min: '0.0'
      max: 1e6
  units: sec
- key: pixel_file
  name: Monitored pixel file
  description: filename for monitored pixel file
  value:
    type: string
    default: '[case_prefix]_outlets.txt'
  units: None
- key: SAVE_Q_PIXELS
  name: Save Q pixels toggle
  description: option to save computed Q time series
  value:
    type: choice
    default: 'Yes'
    choices:
    - 'Yes'
    - 'No'
  units: None
- key: Q_ts_file
  name: Save Q pixels file
  description: filename for computed Q time series
  value:
    type: string
    default: '[case_prefix]_0D-Q.txt'
  units: m^3/s
- key: SAVE_U_PIXELS
  name: Save u pixels toggle
  description: option to save computed u time series
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
  units: None
- key: u_ts_file
  name: Save u pixels file
  description: filename for computed u time series
  value:
    type: string
    default: '[case_prefix]_0D-u.txt'
  units: m/s
- key: SAVE_D_PIXELS
  name: Save d pixels toggle
  description: option to save computed d time series
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
  units: None
- key: d_ts_file
  name: Save d pixels file
  description: filename for computed d time series
  value:
    type: string
    default: '[case_prefix]_0D-d.txt'
  units: m
- key: SAVE_F_PIXELS
  name: Save f pixels toggle
  description: option to save computed f time series
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
  units: None
- key: f_ts_file
  name: Save f pixels file
  description: filename for computed f time series
  value:
    type: string
    default: '[case_prefix]_0D-f.txt'
  units: None
- key: ModelName
  name: Model name
  description: Name of the model
  value:
    type: String
    default: ChannelsDiffWave
  units: None
- key: ModelAuthor
  name: Author name
  description: Name of the model author
  value:
    type: String
    default: 'Scott D. Peckham '
  units: None
- key: HTML_HELP_FILE
  name: HTML help file
  description: URL for HTML help file
  value:
    type: String
    default: http://csdms.colorado.edu/wiki/Model_help:TopoFlow-Channels-Diffusive_Wave
  units: None
