- key: comp_status
  name: Component status
  description: component status {Enabled; Disabled}
  value:
    type: string
    default: Enabled
- key: in_directory
  name: Input directory
  description: input directory
  value:
    type: string
    default: /home/csdms/models/topoflow/3.1/share/data/treynor_iowa/
- key: out_directory
  name: Output directory
  description: output directory
  value:
    type: string
    default: ~/CMT_Output/
- key: site_prefix
  name: Site prefix
  description: file prefix for the study site
  value:
    type: string
    default: Treynor
- key: case_prefix
  name: Case prefix
  description: file prefix for the model scenario
  value:
    type: string
    default: Case5
- key: data_keyword
  name: Data keyword
  description: HIS data keyword
  value:
    type: string
    default: Precipitation
- key: west_edge_lon
  name: West edge longitude
  description: longitude of west edge of geographic region [dec. degrees]
  value:
    type: float
    default: '-111.0'
    range:
      min: '-180.0'
      max: '180.0'
- key: east_edge_lon
  name: East edge longitude
  description: longitude of east edge of geographic region [dec. degrees]
  value:
    type: float
    default: '-110.0'
    range:
      min: '-180.0'
      max: '180.0'
- key: north_edge_lat
  name: North edge latitude
  description: latitude of north edge of geographic region [dec. degrees]
  value:
    type: float
    default: '42.0'
    range:
      min: '-90.0'
      max: '90.0'
- key: south_edge_lat
  name: South edge latitude
  description: latitude of south edge of geographic region [dec. degrees]
  value:
    type: float
    default: '41.0'
    range:
      min: '-90.0'
      max: '90.0'
- key: start_month
  name: Start month
  description: start month {January; February; March; April; May; June; July; August;
    September; October; November; December}
  value:
    type: string
    default: January
- key: start_day
  name: Start day
  description: start day
  value:
    type: int
    default: '1'
    range:
      min: '0'
      max: '31'
- key: start_year
  name: Start year
  description: start year
  value:
    type: int
    default: '1998'
    range:
      min: '1900'
      max: '2020'
- key: stop_month
  name: Stop month
  description: stop month {January; February; March; April; May; June; July; August;
    September; October; November; December}
  value:
    type: string
    default: January
- key: stop_day
  name: Stop day
  description: stop day
  value:
    type: int
    default: '1'
    range:
      min: '0'
      max: '31'
- key: stop_year
  name: Stop year
  description: stop year
  value:
    type: int
    default: '2010'
    range:
      min: '1900'
      max: '2020'
- key: max_n_values
  name: Max values per series
  description: max number of values allowed in any time series
  value:
    type: int
    default: '1000'
    range:
      min: '1'
      max: '1000000'
- key: max_n_series
  name: Max number of series
  description: max number of time series allows in the report
  value:
    type: int
    default: '100'
    range:
      min: '1'
      max: '100000'
- key: save_pixels_dt
  name: Save time series timestep
  description: time interval between time series values [sec]
  value:
    type: float
    default: '60.000'
    range:
      min: '0.0'
      max: 1e6
- key: SAVE_DAT_PIXELS
  name: Save time series toggle
  description: option to save time series {Yes; No}
  value:
    type: string
    default: 'No'
- key: dat_ts_file
  name: Save time series file
  description: filename for time series
  value:
    type: string
    default: '[case_prefix]_0D-data.txt'
- key: ModelName
  name: Model name
  description: Name of the model
  value:
    type: String
    default: DataHIS
- key: ModelAuthor
  name: Author name
  description: Name of the model author
  value:
    type: String
    default: 'Scott D. Peckham '
- key: HTML_HELP_FILE
  name: HTML help file
  description: URL for HTML help file
  value:
    type: String
    default: http://csdms.colorado.edu/wiki/Model_help:TopoFlow-Data-HIS
